name = "SHLocalRegistry"
uuid = "394088ba-16f6-4af4-8a51-5783a2a4253e"
repo = "https://github.com/strangehurst/SHLocalRegistry.git"
description = "StrangeHurst Local Julia Package Registry"

[packages]
1f34f301-fe8c-4464-8328-ff2334f05424 = { name = "PNML", path = "P/PNML" }
